# Generated by Django 3.1.1 on 2020-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='priceperstock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
