# Generated by Django 3.1.1 on 2020-11-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradereq',
            name='priceperstock',
            field=models.FloatField(default=0, null=True),
        ),
    ]
